#!/bin/bash
#curl http://localhost:8080/api/customers -v -X POST -H "Content-Type: application/json" -d "{ \"firstName\" : \"ik\", \"lastName\": \"pil\" }"
#curl http://localhost:8080/api/customers/1 -v -X PUT -H "Content-Type: application/json" -d "{ \"firstName\" : \"ik\", \"lastName\": \"pil\" }"
curl http://localhost:8080/api/customers/1 -v -X DELETE
